# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "azure", "~>0.7"
gem "hashie", "~>3.5"
gem "addressable", "~>2.5"

gem "rdoc", "~>4.0", :group => [:development, :test]
gem "hoe", "~>3.16", :group => [:development, :test]
gem 'rspec', '~> 3.0', :group => [:development, :test]
gem 'simplecov', '~> 0.14', :group => [:development, :test]
# vim: syntax=ruby
